spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/demo
    username: sa
    password:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
